[workspace]
resolver = "2"
members = [
   "RsExample",
   "RsExampleUser",
]

[workspace.dependencies]
everestrs = { git = "https://github.com/qwello/everest-framework.git", rev = "2306559764824a61406da6641985517e3b61f193" }
everestrs-build = { git = "https://github.com/qwello/everest-framework.git", rev = "2306559764824a61406da6641985517e3b61f193" }
